CREATE TABLE [wrestling.ppv] (
    [PPVID]	INT,
    [Event]	VARCHAR(512),
    [PromoID]	INT,
    [Promotion]	VARCHAR(512)
);

INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('1', '#OldSchool', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('2', '10 Reunion', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('3', 'A Night You Can''t Mist', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('4', 'AEW x NJPW: Forbidden Door', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('6', 'Against All Odds', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('7', 'All Glory', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('8', 'All In', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('9', 'All Out', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('10', 'All Star Extravaganza VI', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('11', 'All Star Extravaganza VII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('12', 'All Star Extravaganza VIII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('13', 'Arlington Brawl', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('14', 'Armageddon', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('15', 'Arrival', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('16', 'Back to Cali', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('17', 'Backlash', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('18', 'Backlash France', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('19', 'Bad Blood', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('20', 'Bad Intentions', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('21', 'Badd Blood: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('22', 'Barbed Wire Massacre III', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('23', 'Bash at the Brewery', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('24', 'Bash at the Brewery 2', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('25', 'Battle of Brooklyn', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('26', 'Battleground', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('27', 'BCW 25th Anniversary', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('28', 'Best in the World ''16', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('29', 'Best in the World 2011', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('30', 'Best in the World 2012: Hostage Crisis', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('31', 'Best in the World 2013', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('32', 'Best in the World 2014', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('33', 'Best in the World 2015', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('34', 'Best in the World 2017', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('35', 'Best in the World 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('36', 'Best in the World 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('37', 'Best in the World 2021', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('38', 'Boiling Point', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('39', 'Border Wars', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('40', 'Bound By Honor 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('41', 'Bound By Honor 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('42', 'Bound By Honor 2020', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('43', 'Bound for Glory', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('44', 'Brace for Impact', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('45', 'Bragging Rights', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('46', 'Breakdown: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('47', 'Breaking Point', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('48', 'Caged Collision', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('49', 'Cali Combat', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('50', 'Canadian Clash', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('51', 'Capital Carnage', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('52', 'Capitol Punishment', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('53', 'Clash at the Castle', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('54', 'Clash in the Bluegrass', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('55', 'Clash of Champions', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('56', 'Code Red', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('57', 'Collision in Oklahoma', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('58', 'Confrontation', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('59', 'Critical Transformation', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('60', 'Crockett Cup 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('61', 'Crown Jewel', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('62', 'Cruiserweight Classic Finale', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('63', 'Cyber Sunday', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('64', 'Day 1', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('65', 'Deadline', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('66', 'Death Before Dishonor 2022', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('67', 'Death Before Dishonor 2023', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('68', 'Death Before Dishonor 2024', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('69', 'Death Before Dishonor IX', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('70', 'Death Before Dishonor VIII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('71', 'Death Before Dishonor X: State of Emergency', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('72', 'Death Before Dishonor XI', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('73', 'Death Before Dishonor XIV', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('74', 'Death Before Dishonor XV', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('75', 'Death Before Dishonor XVI', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('76', 'Death Before Dishonor XVII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('77', 'Death Before Dishonor XVII Fallout', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('78', 'Death Before Dishonor XVIII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('79', 'December', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('80', 'December to Dismember', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('81', 'Deep Impact', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('82', 'Destination X', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('83', 'D-Generation X: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('84', 'Digital Destruction', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('85', 'Double or Nothing', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('86', 'Down Under Tour', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('87', 'Driven', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('88', 'Dynasty', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('89', 'ECW One Night Stand', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('90', 'Elimination Chamber', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('91', 'Elimination Chamber: Perth', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('92', 'Emergence', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('93', 'Evolution', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('94', 'Evolve 131: 10th Anniversary Celebration', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('95', 'Extreme Rules', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('96', 'Fastlane', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('97', 'Fatal 4-Way', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('98', 'Fight for the Fallen', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('99', 'Final Battle 2009', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('100', 'Final Battle 2010', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('101', 'Final Battle 2011', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('102', 'Final Battle 2012: Doomsday', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('103', 'Final Battle 2014', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('104', 'Final Battle 2015', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('105', 'Final Battle 2016', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('106', 'Final Battle 2017', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('107', 'Final Battle 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('108', 'Final Battle 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('109', 'Final Battle 2020', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('110', 'Final Battle 2021', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('111', 'Final Battle 2022', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('112', 'Final Battle 2023', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('113', 'Final Resolution', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('114', 'Free Enterprise', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('115', 'Full Gear', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('116', 'Fully Loaded', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('117', 'Fully Loaded: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('118', 'Fyter Fest', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('119', 'G1 Supercard', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('120', 'Gateway To Honor 2020', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('121', 'Genesis', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('122', 'GFW Amped Anthology – Part 1', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('123', 'GFW Amped Anthology – Part 2', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('124', 'GFW Amped Anthology – Part 3', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('125', 'GFW Amped Anthology – Part 4', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('126', 'Global Impact – USA vs. The World', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('127', 'Global Impact 3', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('128', 'Global Impact Japan', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('129', 'Global Wars', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('130', 'Global Wars ''15', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('131', 'Global Wars 2016', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('132', 'Global Wars 2017', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('133', 'Global Wars 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('134', 'Global Wars Espectacular', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('135', 'Glory By Honor IX', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('136', 'Glory By Honor XI: The Unbreakable Hope', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('137', 'Glory By Honor XVI', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('138', 'Glory By Honor XVII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('139', 'Glory By Honor XVIII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('140', 'Gold Rush', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('141', 'Great Balls of Fire', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('142', 'Greatest Royal Rumble', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('143', 'Ground Zero: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('144', 'Gut Check', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('145', 'Halftime Heat', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('146', 'Halloween Havoc', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('147', 'Hard Justice', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('148', 'Hard To Kill', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('149', 'Hardcore Justice', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('150', 'Hardcore Justice 2', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('151', 'Hardcore Justice 3', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('152', 'Hell in a Cell', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('153', 'Homecoming', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('154', 'Honor For All 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('155', 'Honor For All 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('156', 'Honor For All 2021', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('157', 'Honor Reigns Supreme 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('158', 'Honor Reigns Supreme 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('159', 'Honor Reigns Supreme 2020', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('160', 'Honor Re-United', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('161', 'Honor Rising: Japan 2016', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('162', 'Honor Rising: Japan 2017', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('163', 'Honor Rising: Japan 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('164', 'Honor Rising: Japan 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('165', 'Honor Takes Center Stage', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('166', 'Honor United', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('167', 'Honor United 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('168', 'Impact Wrestling vs. Lucha Underground', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('169', 'Impact Wrestling vs. The UK', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('170', 'In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('171', 'In Your House: Beware of Dog', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('172', 'In Your House: Beware of Dog 2', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('173', 'In Your House: Buried Alive', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('174', 'In Your House: Canadian Stampede', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('175', 'In Your House: Cold Day in Hell', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('176', 'In Your House: Final Four', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('177', 'In Your House: Good Friends, Better Enemies', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('178', 'In Your House: International Incident', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('179', 'In Your House: It''s Time', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('180', 'In Your House: Mind Games', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('181', 'In Your House: Revenge of the Taker', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('182', 'Insurrextion', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('183', 'Invasion', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('184', 'Joker''s Wild', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('185', 'Joker''s Wild 2', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('186', 'Judgment Day', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('187', 'Judgment Day: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('188', 'King and Queen of the Ring', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('189', 'King of the Ring', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('190', 'Knockouts Knockdown', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('191', 'Last Chancery', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('192', 'Live from Madison Square Garden', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('193', 'Live!', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('194', 'Lockdown', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('195', 'Lucha Invades NY', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('196', 'Mae Young Classic Finale', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('197', 'Man Up', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('198', 'Manhattan Mayhem 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('199', 'Manhattan Mayhem 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('200', 'March Breakdown', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('201', 'Mass Hysteria', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('202', 'Masters Of The Craft 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('203', 'Masters Of The Craft 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('204', 'Money in the Bank', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('205', 'Motown Showdown', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('206', 'Multiverse of Matches', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('207', 'Multiverse United', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('208', 'Multiverse United 2', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('209', 'New Beginnings', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('210', 'New Horizons', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('211', 'New Year''s Revolution', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('212', 'Night of Champions', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('213', 'Night of the Dummies', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('214', 'No Holds Barred: The Match/The Movie', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('215', 'No Mercy', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('216', 'No Surrender', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('217', 'No Way Out', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('218', 'No Way Out of Texas: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('219', 'Ohio vs. Everything', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('220', 'One Night Only', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('221', 'One Night Stand', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('222', 'Opening Day', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('223', 'Operation Override', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('224', 'Outbreak', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('225', 'Over Drive', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('226', 'Over the Edge', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('227', 'Over the Edge: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('228', 'Over the Limit', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('229', 'Payback', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('230', 'Penta Does Iowa', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('231', 'Prelude to Glory', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('232', 'Rebellion', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('233', 'Rebellion', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('234', 'Redemption', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('235', 'Respect is Earned', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('236', 'Respect is Earned II', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('237', 'Revolution', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('238', 'Rise of the Knockouts', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('239', 'Rising Above', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('240', 'Rivals', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('241', 'Road To G1 Supercard', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('242', 'Roadblock', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('243', 'Roadblock: End of the Line', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('244', 'Rock Bottom: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('245', 'ROH 10th Anniversary Show: Young Wolves Rising', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('246', 'ROH 11th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('247', 'ROH 13th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('248', 'ROH 14th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('249', 'ROH 15th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('250', 'ROH 16th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('251', 'ROH 17th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('252', 'ROH 19th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('253', 'ROH 9th Anniversary Show', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('254', 'ROH Final Battle Fallout', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('255', 'Royal Rumble', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('256', 'Sacrifice', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('257', 'Salute to the Troops', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('258', 'Saturday Night at Center Stage', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('259', 'Saturday Night At Center Stage 2020', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('260', 'September', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('261', 'Showdown in the Sun', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('262', 'Slammiversary', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('263', 'Slammiversary XVI', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('264', 'Slammiversary XVII', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('265', 'Smackville', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('266', 'St. Valentine''s Day Massacre: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('267', 'Stand & Deliver', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('268', 'Star Struck', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('269', 'Starrcade', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('270', 'State Of The Art 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('271', 'State Of The Art 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('272', 'Stomping Grounds', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('273', 'Summer Supercard', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('274', 'SummerSlam', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('275', 'Super ShowDown', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('276', 'Super Show-Down', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('277', 'Supercard of Honor 2023', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('278', 'Supercard of Honor 2024', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('279', 'Supercard of Honor VII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('280', 'Supercard of Honor XI', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('281', 'Supercard of Honor XII', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('282', 'Supercard of Honor XV', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('283', 'Superstar Spectacle', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('284', 'Survival of the Fittest 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('285', 'Survivor Series', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('286', 'Survivor Series: WarGames', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('287', 'Taboo Tuesday', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('288', 'Tag Team Tournament', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('289', 'Take No Prisoners', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('290', 'Take No Prisoners 2009', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('291', 'TakeOver', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('292', 'TakeOver 31', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('293', 'TakeOver 36', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('294', 'TakeOver XXX', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('295', 'TakeOver: Blackpool', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('296', 'TakeOver: Blackpool II', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('297', 'TakeOver: Brooklyn', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('298', 'TakeOver: Brooklyn 4', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('299', 'TakeOver: Brooklyn II', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('300', 'TakeOver: Brooklyn III', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('301', 'TakeOver: Cardiff', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('302', 'TakeOver: Chicago', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('303', 'TakeOver: Chicago II', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('304', 'TakeOver: Dallas', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('305', 'TakeOver: Fatal 4-Way', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('306', 'TakeOver: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('307', 'TakeOver: London', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('308', 'TakeOver: New Orleans', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('309', 'TakeOver: New York', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('310', 'TakeOver: Orlando', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('311', 'TakeOver: Philadelphia', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('312', 'TakeOver: Phoenix', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('313', 'TakeOver: Portland', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('314', 'TakeOver: R Evolution', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('315', 'TakeOver: Respect', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('316', 'TakeOver: Rival', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('317', 'TakeOver: San Antonio', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('318', 'TakeOver: Stand & Deliver', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('319', 'TakeOver: The End', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('320', 'TakeOver: Toronto', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('321', 'TakeOver: Unstoppable', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('322', 'TakeOver: Vengeance Day', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('323', 'TakeOver: WarGames', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('324', 'TakeOver: XXV', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('325', 'Tales From The Ring 3', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('326', 'The Bash', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('327', 'The Beast in the East', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('328', 'The Big Bang!', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('329', 'The Experience 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('330', 'The Great American Bash', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('331', 'The Horror Show at Extreme Rules', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('332', 'The Shield''s Final Chapter', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('333', 'The TNA Classic', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('334', 'The Wrestling Classic', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('335', 'This Tuesday in Texas', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('336', 'Throwback Throwdown II', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('337', 'Throwback Throwdown III', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('338', 'TLC: Tables, Ladders & Chairs', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('339', 'TLC: Tables, Ladders, Chairs... and Stairs', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('340', 'Tournament of Champions', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('341', 'Turning Point', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('342', 'U.K. Championship', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('343', 'Ultra Clash', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('344', 'Unauthorized 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('345', 'Unbreakable', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('346', 'Uncivil War', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('347', 'Undeniable', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('348', 'Under Siege', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('349', 'Unforgiven', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('350', 'Unforgiven: In Your House', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('351', 'United Kingdom Championship Special', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('352', 'United Kingdom Championship Tournament', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('353', 'United We Stand', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('354', 'Vengeance', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('355', 'Vengeance Day', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('356', 'Vengeance: Night of Champions', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('357', 'Victory Road', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('358', 'Victory Road – Knockouts Knockdown', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('359', 'War of the Worlds', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('360', 'War of the Worlds 2017', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('361', 'War of the Worlds 2018', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('362', 'War of the Worlds 2019', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('363', 'War of the Worlds UK: Liverpool', '5', 'Ring of Honor');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('364', 'WarGames', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('365', 'World Cup', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('366', 'Worlds Collide', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('367', 'Worlds End', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('368', 'Worlds End[59]', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('369', 'WrestleDream', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('370', 'WrestleDream[64]', '2', 'AEW');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('371', 'WrestleMania', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('372', 'WrestleMania 13', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('373', 'WrestleMania 2', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('374', 'WrestleMania 2000', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('375', 'WrestleMania 21', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('376', 'WrestleMania 22', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('377', 'WrestleMania 23', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('378', 'WrestleMania 25', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('379', 'WrestleMania 29', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('380', 'WrestleMania 31', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('381', 'WrestleMania 32', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('382', 'WrestleMania 33', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('383', 'WrestleMania 34', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('384', 'WrestleMania 35', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('385', 'WrestleMania 36', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('386', 'WrestleMania 37', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('387', 'WrestleMania 38', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('388', 'WrestleMania 39', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('389', 'WrestleMania Backlash', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('390', 'WrestleMania III', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('391', 'WrestleMania IV', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('392', 'WrestleMania IX', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('393', 'WrestleMania V', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('394', 'WrestleMania VI', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('395', 'WrestleMania VII', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('396', 'WrestleMania VIII', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('397', 'WrestleMania X', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('398', 'WrestleMania X8', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('399', 'WrestleMania XI', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('400', 'WrestleMania XII', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('401', 'WrestleMania XIV', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('402', 'WrestleMania XIX', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('403', 'WrestleMania XL', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('404', 'WrestleMania X-Seven', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('405', 'WrestleMania XV', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('406', 'WrestleMania XX', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('407', 'WrestleMania XXIV', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('408', 'WrestleMania XXVI', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('409', 'WrestleMania XXVII', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('410', 'WrestleMania XXVIII', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('411', 'WrestleMania XXX', '7', 'WWE');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('412', 'X-Travaganza', '6', 'TNA');
INSERT INTO [wrestling.ppv] ([PPVID], [Event], [PromoID], [Promotion]) VALUES ('413', 'Zero Fear', '6', 'TNA');
