CREATE TABLE [wrestling.stables] (
    [Team ID]	INT,
    [Tag Team]	VARCHAR(512),
    [Wrestler ID]	INT,
    [Ring Name]	VARCHAR(512)
);

INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('1', 'ABC', '7', 'Ace Austin');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('1', 'ABC', '102', 'Chris Bey');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('2', 'Alisha Edwards & Masha Slamovich', '22', 'Alisha Edwards');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('2', 'Alisha Edwards & Masha Slamovich', '296', 'Masha Slamovich');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('3', 'A-Town Down Under', '45', 'Austin Theory');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('3', 'A-Town Down Under', '168', 'Grayson Waller');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('4', 'Blackpool Combat Club', '222', 'Jon Moxley');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('4', 'Blackpool Combat Club', '450', 'Wheeler Yuta');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('4', 'Blackpool Combat Club', '83', 'Bryan Danielson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('4', 'Blackpool Combat Club', '107', 'Claudio Castagnoli');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('4', 'Blackpool Combat Club', '451', 'Wheeler Yuta');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('4', 'Blackpool Combat Club', '108', 'Claudio Castagnoli');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '43', 'Austin Gunn');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '115', 'Colten Gunn');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '202', 'Jay White');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '228', 'Juice Robinson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '44', 'Austin Gunn');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '116', 'Colten Gunn');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('5', 'Bullet Club Gold', '203', 'Jay White');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('6', 'Candice LeRae & Indi Hartwell', '87', 'Candice LeRae');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('6', 'Candice LeRae & Indi Hartwell', '181', 'Indi Hartwell');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('7', 'Chase University', '24', 'Andre Chase');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('7', 'Chase University', '144', 'Duke Hudson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('7', 'Chase University', '371', 'Riley Osborne');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('7', 'Chase University', '427', 'Thea Hail');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('8', 'Chelsea Green & Piper Niven', '101', 'Chelsea Green');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('8', 'Chelsea Green & Piper Niven', '352', 'Piper Niven');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('9', 'Cole Karter & Griff Garrison', '112', 'Cole Karter');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('9', 'Cole Karter & Griff Garrison', '169', 'Griff Garrison');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('9', 'Cole Karter & Griff Garrison', '113', 'Cole Karter');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('9', 'Cole Karter & Griff Garrison', '170', 'Griff Garrison');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('10', 'Damage CTRL', '40', 'Asuka');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('10', 'Damage CTRL', '120', 'Dakota Kai');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('10', 'Damage CTRL', '186', 'Iyo Sky');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('10', 'Damage CTRL', '231', 'Kairi Sane');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('11', 'Dark Order', '20', 'Alex Reynolds');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('11', 'Dark Order', '160', 'Evil Uno');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('11', 'Dark Order', '218', 'John Silver');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('12', 'Death Triangle', '343', 'Pac');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('12', 'Death Triangle', '349', 'Penta El Zero Miedo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('12', 'Death Triangle', '361', 'Rey Fénix');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('13', 'Decay', '176', 'Havok');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('13', 'Decay', '376', 'Rosemary');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('14', 'Diamante and Mercedes Martinez', '136', 'Diamanté');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('14', 'Diamante and Mercedes Martinez', '308', 'Mercedes Martinez');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('14', 'Diamante and Mercedes Martinez', '137', 'Diamanté');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('14', 'Diamante and Mercedes Martinez', '309', 'Mercedes Martinez');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('15', 'DIY', '220', 'Johnny Gargano');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('15', 'DIY', '432', 'Tommaso Ciampa');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('16', 'Edris Enofe & Malik Blade', '152', 'Edris Enofé');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('16', 'Edris Enofe & Malik Blade', '287', 'Malik Blade');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('17', 'Final Testament', '16', 'Akam');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('17', 'Final Testament', '235', 'Karrion Kross');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('17', 'Final Testament', '363', 'Rezar');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('17', 'Final Testament', '390', 'Scarlett');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('18', 'First Class', '14', 'AJ Francis');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('18', 'First Class', '366', 'Rich Swann');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('19', 'FTR', '94', 'Cash Wheeler');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('19', 'FTR', '133', 'Dax Harwood');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('20', 'Gallus', '214', 'Joe Coffey');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('20', 'Gallus', '293', 'Mark Coffey');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('20', 'Gallus', '454', 'Wolfgang');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('21', 'Hank Walker & Tank Ledger', '173', 'Hank Walker');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('21', 'Hank Walker & Tank Ledger', '418', 'Tank Ledger');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('22', 'Imperium', '171', 'Gunther');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('22', 'Imperium', '282', 'Ludwig Kaiser');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('23', 'Iron Savages', '66', 'Boulder');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('23', 'Iron Savages', '78', 'Bronson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('23', 'Iron Savages', '67', 'Boulder');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('23', 'Iron Savages', '79', 'Bronson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('24', 'Jacy Jayne & Jazmyn Nyx', '192', 'Jacy Jayne');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('24', 'Jacy Jayne & Jazmyn Nyx', '204', 'Jazmyn Nyx');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('25', 'Jade Cargill & Bianca Belair', '53', 'Bianca Belair');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('25', 'Jade Cargill & Bianca Belair', '193', 'Jade Cargill');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('26', 'Judgement Day', '122', 'Damian Priest');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('26', 'Judgement Day', '1', '""Dirty"" Dominik Mysterio');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('26', 'Judgement Day', '162', 'Finn Bálor');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('26', 'Judgement Day', '206', 'JD McDonagh');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('26', 'Judgement Day', '364', 'Rhea Ripley');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('27', 'Katana Chance & Kayden Carter', '236', 'Katana Chance');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('28', 'La Faccion Ingobernable', '142', 'Dralístico');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('28', 'La Faccion Ingobernable', '354', 'Preston Vance');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('28', 'La Faccion Ingobernable', '380', 'Rush');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('29', 'Legado Del Fantasma', '25', 'Angel');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('29', 'Legado Del Fantasma', '50', 'Berto');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('29', 'Legado Del Fantasma', '153', 'Elektra Lopez');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('29', 'Legado Del Fantasma', '386', 'Santos Escobar');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('30', 'LWO', '119', 'Cruz Del Toro');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('30', 'LWO', '141', 'Dragon Lee');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('30', 'LWO', '212', 'Joaquin Wilde');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('30', 'LWO', '362', 'Rey Mysterio');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('30', 'LWO', '461', 'Zelina Vega');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('31', 'Meta-Four', '196', 'Jakara Jackson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('31', 'Meta-Four', '267', 'Lash Legend');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('31', 'Meta-Four', '334', 'Noam Dar');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('31', 'Meta-Four', '340', 'Oro Mensah');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('32', 'New Catch Republic', '350', 'Pete Dunne');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('32', 'New Catch Republic', '442', 'Tyler Bate');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('33', 'Out the Mud', '77', 'Bronco Nima');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('33', 'Out the Mud', '195', 'Jaida Parker');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('33', 'Out the Mud', '281', 'Lucien Price');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('34', 'Pretty Deadly', '154', 'Elton Prince');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('34', 'Pretty Deadly', '251', 'Kit Wilson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('35', 'Private Party ', '182', 'Isiah Kassidy');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('35', 'Private Party ', '295', 'Marq Quen');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('36', 'Shane Taylor Promotions', '33', 'Anthony Ogogo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('36', 'Shane Taylor Promotions', '270', 'Lee Moriarty');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('36', 'Shane Taylor Promotions', '395', 'Shane Taylor');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('36', 'Shane Taylor Promotions', '271', 'Lee Moriarty');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('36', 'Shane Taylor Promotions', '396', 'Shane Taylor');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('37', 'Shayna Baszler & Zoey Stark', '400', 'Shayna Baszler');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('37', 'Shayna Baszler & Zoey Stark', '462', 'Zoey Stark');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('38', 'Speedball Mountain', '312', 'Mike Bailey');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('38', 'Speedball Mountain', '438', 'Trent Seven');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('39', 'Spitfire', '125', 'Dani Luna');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('39', 'Spitfire', '213', 'Jody Threat');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('40', 'The Acclaimed', '31', 'Anthony Bowens');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('40', 'The Acclaimed', '58', 'Billy Gunn');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('40', 'The Acclaimed', '304', 'Max Caster');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('41', 'The Alpha Academy', '17', 'Akira Tozawa');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('41', 'The Alpha Academy', '96', 'Chad Gable');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('41', 'The Alpha Academy', '305', 'Maxxine Dupri');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('41', 'The Alpha Academy', '342', 'Otis');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('42', 'The Awesome Truth', '378', 'R-Truth');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('42', 'The Awesome Truth', '426', 'The Miz');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('43', 'The Bloodline', '211', 'Jimmy Uso');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('43', 'The Bloodline', '375', 'Roman Reigns');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('43', 'The Bloodline', '345', 'Paul Heyman');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('43', 'The Bloodline', '408', 'Solo Sikoa');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('43', 'The Bloodline', '416', 'Tama Tonga');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('43', 'The Bloodline', '433', 'Tonga Loa');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('44', 'The Butcher and The Blade', '424', 'The Blade');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('44', 'The Butcher and The Blade', '425', 'The Butcher');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('45', 'The D''Angelo Family', '434', 'Tony D''Angelo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('45', 'The D''Angelo Family', '12', 'Adriana Rizzo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('45', 'The D''Angelo Family', '97', 'Channing ""Stacks"" Lorenzo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('45', 'The D''Angelo Family', '280', 'Luca Crusifino');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('46', 'The Diamond Mine', '82', 'Brutus Creed');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('46', 'The Diamond Mine', '185', 'Ivy Nile');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('46', 'The Diamond Mine', '230', 'Julius Creed');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '452', 'Will Ospreay');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '260', 'Kyle Fletcher');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '256', 'Konosuke Takeshita');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '294', 'Mark Davis');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '353', 'Powerhouse Hobbs');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '437', 'Trent Beretta');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('47', 'The Don Callis Family', '261', 'Kyle Fletcher');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('48', 'The Elite', '239', 'Kazuchika Okada');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('48', 'The Elite', '303', 'Matthew Jackson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('48', 'The Elite', '329', 'Nicholas Jackson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('48', 'The Elite', '68', 'Brandon Cutler');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('48', 'The Elite', '188', 'Jack Perry');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('49', 'The Gates of Agony', '59', 'Bishop Kaun');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('49', 'The Gates of Agony', '70', 'Brian Cage');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('49', 'The Gates of Agony', '430', 'Toa Liona');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('49', 'The Gates of Agony', '60', 'Bishop Kaun');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('49', 'The Gates of Agony', '71', 'Brian Cage');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('49', 'The Gates of Agony', '431', 'Toa Liona');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('50', 'The Good Hands', '199', 'Jason Hotch');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('50', 'The Good Hands', '219', 'John Skyler');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('51', 'The House of Black', '75', 'Brody King');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('51', 'The House of Black', '85', 'Buddy Matthews');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('51', 'The House of Black', '229', 'Julia Hart');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('51', 'The House of Black', '286', 'Malakai Black');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('52', 'The Infantry', '89', 'Carlie Bravo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('52', 'The Infantry', '397', 'Shawn Dean');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('52', 'The Infantry', '90', 'Carlie Bravo');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('52', 'The Infantry', '398', 'Shawn Dean');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('52', 'The Infantry', '441', 'Trish Adora');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('53', 'The Learning Tree', '103', 'Chris Jericho');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('53', 'The Learning Tree', '54', 'Big Bill');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('53', 'The Learning Tree', '84', 'Bryan Keith');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('54', 'The New Day', '252', 'Kofi Kingston');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('54', 'The New Day', '456', 'Xavier Woods');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('55', 'The O.C.', '15', 'AJ Styles');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('55', 'The O.C.', '233', 'Karl Anderson');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('55', 'The O.C.', '283', 'Luke Gallows');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('55', 'The O.C.', '311', 'Michin');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('56', 'The Outcasts', '174', 'Harley Cameron');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('56', 'The Outcasts', '387', 'Saraya');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('57', 'The Patriarchy', '3', '""The Prodigy"" Nick Wayne');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('57', 'The Patriarchy', '104', 'Christian Cage');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('57', 'The Patriarchy', '248', 'Killswitch');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('58', 'The Pride', '28', 'Angelo Dawkins');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('58', 'The Pride', '51', 'B-Fab');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('58', 'The Pride', '65', 'Bobby Lashley');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('58', 'The Pride', '318', 'Montez Ford');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('59', 'The Rascals', '439', 'Trey Miguel');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('59', 'The Rascals', '459', 'Zachary Wentz');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('60', 'The Righteous', '146', 'Dutch');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('60', 'The Righteous', '446', 'Vincent');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('61', 'The Supersonic Duo', '46', 'Axiom');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('61', 'The Supersonic Duo', '326', 'Nathan Frazer');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('62', 'The System', '319', 'Moose');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('62', 'The System', '72', 'Brian Myers');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('62', 'The System', '148', 'Eddie Edwards');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '301', 'Matt Taven');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '313', 'Mike Bennett');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '9', 'Adam Cole');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '374', 'Roderick Strong');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '447', 'Wardlow');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Viking Raiders', '158', 'Erik');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Viking Raiders', '445', 'Valhalla');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Viking Raiders', '184', 'Ivar');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '302', 'Matt Taven');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('63', 'The Undisputed Kingdom', '314', 'Mike Bennett');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('64', 'The Unholy Union', '19', 'Alba Fyre');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('64', 'The Unholy Union', '183', 'Isla Dawn');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('64', 'The WorkHorsemen', '32', 'Anthony Henry');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('64', 'The WorkHorsemen', '205', 'JD Drake');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('65', 'Top Flight', '8', 'Action Andretti');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('65', 'Top Flight', '130', 'Dante Martin');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('65', 'Top Flight', '132', 'Darius Martin');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('66', 'Varsity Athletes', '36', 'Ari Daivari');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('66', 'Varsity Athletes', '227', 'Josh Woods');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('66', 'Varsity Athletes', '435', 'Tony Nese');
INSERT INTO [wrestling.stables] ([Team ID], [Tag Team], [Wrestler ID], [Ring Name]) VALUES ('66', 'Varsity Athletes', '436', 'Tony Nese');
